services:
  customer:
    image: customer:latest
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8001
      - APP_SECRET=${APP_SECRET}
      - MONGODB_URI=${MONGODB_URI}/customer_db?retryWrites=true&w=majority
      - MSG_QUEUE_URL=${MSG_QUEUE_URL}
      - EXCHANGE_NAME=ONLINE_STORE

  products:
    image: products:latest
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8002
      - APP_SECRET=${APP_SECRET}
      - MONGODB_URI=${MONGODB_URI}/products_db?retryWrites=true&w=majority
      - MSG_QUEUE_URL=${MSG_QUEUE_URL}
      - EXCHANGE_NAME=ONLINE_STORE

  shopping:
    image: shopping:latest
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8003
      - APP_SECRET=${APP_SECRET}
      - MONGODB_URI=${MONGODB_URI}/shopping_db?retryWrites=true&w=majority
      - MSG_QUEUE_URL=${MSG_QUEUE_URL}
      - EXCHANGE_NAME=ONLINE_STORE

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - customer
      - products
      - shopping
    restart: always
